### ISSUE TITLE
想使用自定义的方式修改默认语句，替换Something is Wrong，但是Component.prototype.isPrototypeOf(Boundary.prototype)校验一直不通过

### ISSUE THREAD

**Issue by xy2cq** [x-orpheus/catch-react-error#4]
大大能帮忙看下么，自定义的组件（直接复制readme里的）已经是继承了React.Component，但是Component.prototype.isPrototypeOf(Boundary.prototype)的校验一直不通过，导致一直替换不了默认的DefaultErrorBoundary，想问问是我代码写得哪里有问题
引用：
`
import catchreacterror from 'catch-react-error'
import CustomErrorBoundary from './error'
console.log(CustomErrorBoundary.prototype, !React.Component.prototype.isPrototypeOf(CustomErrorBoundary.prototype))
@catchreacterror(CustomErrorBoundary)
`

error.js

`
import * as React from 'react'
export class DefaultErrorBoundary extends React.Component {
    state= {
      hasError: false,
    }
    static getDerivedStateFromError(err) {
      return {
        hasError: true,
        err
      }
    }
    componentDidCatch(err, info) {
      console.log(err, info)
    }

    render() {
      if (this.state.hasError) {
        return <div>报错信息</div>
      }
      return this.props.children
    }
}
export default DefaultErrorBoundary
`

**Comment by xff1874** [comment]
> 大大能帮忙看下么，自定义的组件（直接复制readme里的）已经是继承了React.Component，但是Component.prototype.isPrototypeOf(Boundary.prototype)的校验一直不通过，导致一直替换不了默认的DefaultErrorBoundary，想问问是我代码写得哪里有问题
> 引用：
> `import catchreacterror from 'catch-react-error' import CustomErrorBoundary from './error' console.log(CustomErrorBoundary.prototype, !React.Component.prototype.isPrototypeOf(CustomErrorBoundary.prototype)) @catchreacterror(CustomErrorBoundary)`
> 
> error.js
> 
> `
> import * as React from 'react'
> export class DefaultErrorBoundary extends React.Component {
> state= {
> hasError: false,
> }
> static getDerivedStateFromError(err) {
> return {
> hasError: true,
> err
> }
> }
> componentDidCatch(err, info) {
> console.log(err, info)
> }
> 
> ```
> render() {
>   if (this.state.hasError) {
>     return <div>报错信息</div>
>   }
>   return this.props.children
> }
> ```
> 
> }
> export default DefaultErrorBoundary
> `

问题已经解决，请更新最新的版本，同时我们在demo里面添加了对应的例子，可以参考。

> 大大能帮忙看下么，自定义的组件（直接复制readme里的）已经是继承了React.Component，但是Component.prototype.isPrototypeOf(Boundary.prototype)的校验一直不通过，导致一直替换不了默认的DefaultErrorBoundary，想问问是我代码写得哪里有问题
> 引用：
> `import catchreacterror from 'catch-react-error' import CustomErrorBoundary from './error' console.log(CustomErrorBoundary.prototype, !React.Component.prototype.isPrototypeOf(CustomErrorBoundary.prototype)) @catchreacterror(CustomErrorBoundary)`
> 
> error.js
> 
> `
> import * as React from 'react'
> export class DefaultErrorBoundary extends React.Component {
> state= {
> hasError: false,
> }
> static getDerivedStateFromError(err) {
> return {
> hasError: true,
> err
> }
> }
> componentDidCatch(err, info) {
> console.log(err, info)
> }
> 
> ```
> render() {
>   if (this.state.hasError) {
>     return <div>报错信息</div>
>   }
>   return this.props.children
> }
> ```
> 
> }
> export default DefaultErrorBoundary
> `

问题已经解决，请更新最新版本，同时我们在example-server和example-client添加了对于的例子，可以参考一下。
